### ISSUE TITLE
Neon interface is not being displayed in Rodan

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/neon-wrapper#21]
This could be an issue of the Rodan-docker repo. 

When opening the interactive Neon job from the Rodan interface (in local development), the app interface is not being displayed. 

rodan-celery logs are fine: 

```
[2019-08-15 18:20:28,526: INFO/MainProcess] Received task: Neon[dd9fef48-6122-4536-a99d-8b9f4121cbbe]
[2019-08-15 18:20:28,660: INFO/MainProcess] Task Neon[dd9fef48-6122-4536-a99d-8b9f4121cbbe] succeeded in 0.131941513999s: 'WAITING FOR INPUT'
```

but gunicorn queue logs throw warnings:

`gunicorn-access`
```
172.18.0.9 - - [15/Aug/2019:18:37:16 -0400] "GET /interactive/0339ef83-853e-47fa-9ab1-162d4015c2b8/04c11b80-ab41-4165-845e-7fd724c0a687/editor.js HTTP/1.0" 500 27 "http://localhost/interactive/0339ef83-853e-47fa-9ab1-162d4015c2b8/04c11b80-ab41-4165-845e-7fd724c0a687/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
```

`gunicorn-error`
```
[2019-08-15 18:37:16 +0000] [77] [DEBUG] GET /interactive/0339ef83-853e-47fa-9ab1-162d4015c2b8/04c11b80-ab41-4165-845e-7fd724c0a687/editor.js
```

**Comment by vigliensoni** [comment]
Actually, the Rodan container console is giving this error, which seems to be the culprit:

```
ERROR Internal Server Error: /interactive/0339ef83-853e-47fa-9ab1-162d4015c2b8/04c11b80-ab41-4165-845e-7fd724c0a687/editor.js
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/Rodan/rodan/views/interactive.py", line 166, in get
    with open(abspath, "rb") as fsock:
IOError: [Errno 2] No such file or directory: u'/code/Rodan/rodan/jobs/neon-wrapper/static/editor.js'
```

In the repo, `editor.js` is actually located at `/code/Rodan/rodan/jobs/neon-wrapper/static.js` and not it `/code/Rodan/rodan/jobs/neon-wrapper/static/editor.js`

**Comment by vigliensoni** [comment]
The `static` folder and all its elements are not being created. The script triggered in https://github.com/DDMAL/neon-wrapper/blob/c76fdd0bf15f831e735906028894c19231516ce2/package.json#L27-L29 is not being executed in the Rodan-docker install.

**Comment by vigliensoni** [comment]
For local development, the full installation of the neon-wrapper should follow

```
# Install Neon
git clone --recurse-submodules -b develop https://github.com/DDMAL/neon-wrapper
cd ./neon-wrapper
git submodule update --init
yarn install
yarn build
```
